name: Continuous Integration

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies backend
        run: npm install
        working-directory: ./Back-End

      - name: Start API server
        run: |
          nohup node server.js &
          sleep 5
        working-directory: ./Back-End

      - name: Run API tests with Newman
        run: |
          npm install -g newman
          newman run ./Tests/Postman/Newman.postman_collection.json
